### ISSUE TITLE
No Images Found

### ISSUE THREAD

**Issue by pavanagrawal123** [madjam002/pix#1]
Hi!

I'm running this on my CentOS VM via Docker, but it doesn't find any photos I have my photos stored in /photos/. I see the index working, but in the docker window it just shows Indexing:
worker_1  | Indexing /photos
worker_1  | Got 0 photos
I can send any debug logs you need! Thanks for this awesome software....

**Comment by madjam002** [comment]
Hi there,

Thanks for trying it out! Have you edited `docker-compose.yml` to mount your photos directory into the worker and server containers?

See: https://github.com/madjam002/pix/blob/master/docker-compose.yml#L17

If you have your photos in `/photos` on your CentOS VM, you'll need to change it to something like:

```
volumes:
  - "pix_data:/mnt/data"
  - "/photos:/photos"
```

This ensures that `/photos` is accessible inside the Docker containers. Make sure you do it for `server` and `worker`. Run `docker-compose up -d` after to make sure your changes are applied.

If you've already done this and it's still not working - I'm not sure what the issue could be. Maybe try running `docker-compose exec worker ls /photos` and see if your photos are there.

Also make sure you're up to date as I'm pushing new updates quite often - you can update with `docker-compose pull` and `docker-compose up -d`.

Cheers

**Comment by pavanagrawal123** [comment]
Hi!
 
Yes, that was the problem, images are showing up now. Thanks. However, the thumbs are not showing up on the UI. I can see in the docker console log that it is generating, but I am seeing a connection refused in the dev console while loading the thumbnail’s jpg. 
 
Thanks.

**Comment by madjam002** [comment]
What URL are you accessing Pix on? You need to make sure that you configure the PIX_URL environment variable as well with this URL. See https://github.com/madjam002/pix/blob/master/docker-compose.yml#L14 (make sure you set it for `worker` too).

I hope to make the installation simpler in the future and clearer.

**Comment by pavanagrawal123** [comment]
Hi, that worked. I added a pull request to make the instructions clearer.

**Comment by madjam002** [comment]
Brilliant, glad you've got it working! I've also merged your pull request :smile:
