### ISSUE TITLE
Thumbnail page not displaying all thumbnails

### ISSUE THREAD

**Issue by jmturner** [madjam002/pix#4]
I'm running the latest branch via Docker and pointing Pix to my NFS share of photos. It seems Pix indexes them but only the first 40 or so photos appear on the thumbnail page.

The other photos are there and can be navigated left and right from the photo page but not having them show on the thumbnail page omits the right-click option for viewing and downloading them. Thanks!

**Comment by jmturner** [comment]
I suspect this heap out of memory issue is to blame. The worker consistently segfaults around 192-ish photos indexed:

Jul 11 22:29:31 picasso journal: Complete 190 left 8503
Jul 11 22:29:31 picasso journal: Complete 191 left 8502
Jul 11 22:29:31 picasso journal: Complete 192 left 8501
Jul 11 22:29:31 picasso journal: Checking September/September 4-9, 2007/DSCF5153.jpg
Jul 11 22:29:31 picasso journal: Updating parent folder for item September/September 4-9, 2007/DSCF5153.jpg
Jul 11 22:29:32 picasso journal: Processing new item September/September 24, 2007/DSCF7028.jpg
Jul 11 22:29:35 picasso journal: **FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**
Jul 11 22:29:35 picasso journal: 1: node::Abort() [node]
Jul 11 22:29:35 picasso journal: 2: 0xfb0b6c [node]
Jul 11 22:29:35 picasso journal: 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
Jul 11 22:29:35 picasso journal: 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
Jul 11 22:29:35 picasso journal: 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
Jul 11 22:29:35 picasso journal: 6: 0xc0bd7f [node]
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal: <--- Last few GCs --->
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal:   32307 ms: Mark-sweep 607.3 (642.9) -> 597.6 (642.9) MB, 199.7 / 0 ms [allocation failure] [GC in old space requested].
Jul 11 22:29:35 picasso journal:   32498 ms: Mark-sweep 597.6 (642.9) -> 597.3 (641.9) MB, 191.3 / 0 ms [allocation failure] [GC in old space requested].
Jul 11 22:29:35 picasso journal:   32697 ms: Mark-sweep 597.3 (641.9) -> 597.3 (638.9) MB, 198.8 / 0 ms [last resort gc].
Jul 11 22:29:35 picasso journal:   32879 ms: Mark-sweep 597.3 (638.9) -> 597.3 (638.9) MB, 182.3 / 0 ms [last resort gc].
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal: <--- JS stacktrace --->
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal: ==== JS stack trace =========================================
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal: Security context: 0xb6b07ac9e59 <JS Object>
Jul 11 22:29:35 picasso journal:    2: readTag [/usr/src/app/pix-server/node_modules/exif-reader/index.js:~73] [pc=0x26dbe2858ac9] (this=0xb6b07ae07f9 <JS Global Object>,buffer=0xea2d8f57bb9 <an Uint8Array with map 0x3d4882882011>,offset=126,bigEndian=0xb6b07a04231 <true>)
Jul 11 22:29:35 picasso journal:    3: readTags [/usr/src/app/pix-server/node_modules/exif-reader/index.js:59] [pc=0x26dbe28555a5] (this=0xb6b07ae07f9 <JS Global Object>,buffer=0xea2d8f57b...
Jul 11 22:29:35 picasso journal: 
Jul 11 22:29:35 picasso journal: 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
Jul 11 22:29:35 picasso journal: 8: 0x26dbe2006338

**Comment by jmturner** [comment]
Any interest in poking around with this again?

**Comment by madjam002** [comment]
@jmturner Hey, thanks for your interest, unfortunately I have no time to pick this up again at the moment.

**Comment by jmturner** [comment]
For some reason I only now tried rendering a folder using Chrome, and - guess what - it works fine. So something in Firefox is broken.

**Comment by jmturner** [comment]
I stand corrected. It works on my Chrome on Ubuntu ver 52.xx but not on Chrome for Windows ver 67. I am really confused now.

**Comment by jmturner** [comment]
Another clue. I upgraded my Ubuntu Chrome ver from 52.0.2743.116-1 to 67.0.3396.87-1. Now it only shows 70-75 images in a folder again. It appears that a library or libraries which used to work no longer work with the newest browsers?
